# Generated by Django 4.2.1 on 2023-05-30 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="phone",
        ),
        migrations.AlterField(
            model_name="contact",
            name="desc",
            field=models.CharField(max_length=500),
        ),
    ]
